<?php
require_once "../config.php";
require_once "../vendor/autoload.php";
include "../classes/EMIScheduleManager.php";
include_once "../classes/class.Input.php";

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Border;
use TCPDF;

if (isset($_GET['export'])) {
    $exportType = $_GET['export'];
    $iBorrowerId = Input::request('borrowerId');
    $dFromDate = Input::request('sFromDate') ?? '';
    $dToDate = Input::request('sToDate') ?? '';
    $sLoanAmount = Input::request('sLoanAmount') ?? '';

    $emiManager = new EMIScheduleManager();
    $oEMISchedules = $emiManager->getAllEMISchedulesByBorrowerId($iBorrowerId, $dFromDate, $dToDate, $sLoanAmount);

    $filteredBorrowers = formatBorrowerData($oEMISchedules);

    if ($exportType === 'excel') {
        exportToExcel($filteredBorrowers);
    } elseif ($exportType === 'pdf') {
        exportToPDF($filteredBorrowers);
    }
}

function formatBorrowerData($borrowers)
{
    return array_map(function ($borrower, $index) {
        return [
            'Sr. No' => $index + 1,
            'Borrower Name' => $borrower['name'] ?? '',
            'Pending Amount (Interest/EMI)' => $borrower['emi_amount'] ?? '',
            'Principal Repaid' => $borrower['principal_repaid'] ?? '',
            'Outstanding Principal' => $borrower['ending_principal'] ?? '',
            'Due Date' => $borrower['payment_due_date'] ?? '',
            'Status' => $borrower['payment_status'] ?? '',
        ];
    }, $borrowers, array_keys($borrowers));
}

function exportToExcel($data)
{
    $spreadsheet = new Spreadsheet();
    $sheet = $spreadsheet->getActiveSheet();

    // Set title
    $sheet->setCellValue('A1', 'Pending Payment')
        ->mergeCells('A1:G1')
        ->getStyle('A1')->getFont()->setBold(true)->setSize(16);
    $sheet->getStyle('A1')->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);

    // Add header row
    $headers = array_keys($data[0]);
    $sheet->fromArray($headers, null, 'A2');
    $sheet->getStyle('A2:G2')->getFont()->setBold(true);
    $sheet->getStyle('A2:G2')->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);

    // Add data rows
    $row = 3;
    foreach ($data as $borrower) {
        $sheet->fromArray(array_values($borrower), null, "A$row");
        $row++;
    }

    // Adjust column widths and styles
    foreach (range('A', 'G') as $col) {
        $sheet->getColumnDimension($col)->setAutoSize(true);
        $sheet->getStyle($col)->getAlignment()->setWrapText(true);
    }

    $lastRow = $row - 1;
    $sheet->getStyle("A2:G$lastRow")->getBorders()->getAllBorders()->setBorderStyle(Border::BORDER_THIN);

    // Output file
    outputExcel($spreadsheet, 'Pending Payment');
}

function outputExcel($spreadsheet, $filename)
{
    $writer = new Xlsx($spreadsheet);
    $filename .= "_" . date("Y-m-d_H-i-s") . ".xlsx";

    header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    header("Content-Disposition: attachment; filename=$filename");
    $writer->save("php://output");
    exit;
}

function exportToPDF($data)
{
    $pdf = new TCPDF();
    $pdf->SetCreator(PDF_CREATOR);
    $pdf->SetAuthor('Web App Loan');
    $pdf->SetTitle('Pending Payment');
    $pdf->SetHeaderData('', 0, 'Pending Payment', 'Generated by Web App Loan', [0, 64, 255], [0, 64, 128]);
    $pdf->setFooterData([0, 64, 0], [0, 64, 128]);
    $pdf->SetMargins(10, 20, 10);
    $pdf->SetHeaderMargin(5);
    $pdf->SetFooterMargin(10);
    $pdf->SetAutoPageBreak(true, 20);
    $pdf->AddPage();

    $html = generatePDFHTML($data);
    $pdf->writeHTML($html, true, false, true, false, '');

    $filename = "Pending_Payment_" . date("Y-m-d_H-i-s") . ".pdf";
    $pdf->Output($filename, 'D');
    exit;
}

function generatePDFHTML($data)
{
    $html = '<h2 style="text-align:center; font-size:16px;">Pending Payment</h2>';
    $html .= '<table border="1" cellpadding="5" cellspacing="0" style="width:100%; border-collapse: collapse; font-size:10pt;">
                <thead>
                    <tr style="background-color: #f2f2f2; font-weight: bold;">
                        <th>Sr. No</th>
                        <th>Borrower Name</th>
                        <th>Pending Amount (Interest/EMI)</th>
                        <th>Principal Repaid</th>
                        <th>Outstanding Principal</th>
                        <th>Due Date</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>';

    foreach ($data as $row) {
        $html .= '<tr>';
        foreach ($row as $cell) {
            $html .= "<td style='text-align: center;'>$cell</td>";
        }
        $html .= '</tr>';
    }

    $html .= '</tbody></table>';
    return $html;
}
