<?php
require_once "../config.php";
require_once "../vendor/autoload.php";
include_once "../classes/class.Input.php";
include_once "../classes/LoanPaymentManager.php";

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use TCPDF;

if (isset($_GET['export'])) {
    $exportType = $_GET['export'];
    $name = Input::request('name') ?? '';
    $dFromDate = Input::request('sFromDate')??'';
    $dToDate = Input::request('sToDateFilter')??'';
    $paymentMode = Input::request('paymentMode') ?? '';
    // Fetch loan details based on filters

    $oLoanPaymentManager = new LoanPaymentManager();
    $paymentData = $oLoanPaymentManager->getAllLoanPaymentsGlobal($name, $dFromDate,$dToDate, $paymentMode);


    // Prepare filtered data
    $filteredData = array_map(function ($loan, $index) {
        return [
            'Sr. No'            => $index + 1,
            'Borrower Name'     => $loan['name'] ?? '',
            'Payment Amount'    => number_format((float)($loan['payment_amount'] ?? 0), 2),
            'Penalty'           => number_format((float)($loan['penalty_amount'] ?? 0), 2),
            'Referral Share'    => number_format((float)($loan['referral_share_amount'] ?? 0), 2),
            'Payment Mode'      => $loan['mode_of_payment'] ?? '', // Assuming mode is not numeric
            'Received Date'     => date('Y-m-d', strtotime($loan['received_date'] ?? '')),
            'Due Date'          => date('Y-m-d', strtotime($loan['interest_date'] ?? '')),
            'Status'            => ucfirst($loan['payment_status'] ?? 'Unknown'),
        ];
    }, $paymentData, array_keys($paymentData));

    if ($exportType === 'excel') {
        exportToExcel($filteredData);
    } elseif ($exportType === 'pdf') {
        exportToPDF($filteredData);
    }
}



// Export to Excel
function exportToExcel($data)
{
    $spreadsheet = new Spreadsheet();
    $sheet = $spreadsheet->getActiveSheet();

    // Set title and headings
    $sheet->setCellValue('A1', 'Loan Management Report');
    $sheet->mergeCells('A1:F1');
    $sheet->getStyle('A1')->getFont()->setBold(true)->setSize(14);
    $sheet->getRowDimension('1')->setRowHeight(30);

    // Add header row
    $headers = array_keys($data[0]);
    $sheet->fromArray($headers, null, 'A2');

    // Add data rows
    $row = 3;
    foreach ($data as $record) {
        $sheet->fromArray(array_values($record), null, "A$row");
        $row++;
    }

    // Auto-size columns
    foreach (range('A', 'F') as $col) {
        $sheet->getColumnDimension($col)->setAutoSize(true);
    }

    // Write file
    $writer = new Xlsx($spreadsheet);
    $filename = "Loan_Report_" . date("Y-m-d_H-i-s") . ".xlsx";

    // Output to browser
    header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    header("Content-Disposition: attachment; filename=$filename");
    $writer->save("php://output");
    exit;
}

// Export to PDF
function exportToPDF($data)
{
    $pdf = new TCPDF();
    $pdf->SetCreator(PDF_CREATOR);
    $pdf->SetAuthor('Web App Loan');
    $pdf->SetTitle('Loan Report');
    $pdf->SetHeaderData('', 0, 'Loan Report', 'Generated by Web App Loan', [0, 64, 255], [0, 64, 128]);
    $pdf->setFooterData([0, 64, 0], [0, 64, 128]);
    $pdf->SetMargins(10, 20, 10);
    $pdf->SetHeaderMargin(5);
    $pdf->SetFooterMargin(10);
    $pdf->SetAutoPageBreak(true, 20);
    $pdf->AddPage();

    // Generate table HTML
    $html = '<h2 style="text-align:center;">Loan Report</h2>';
    $html .= '<table border="1" cellpadding="5" cellspacing="0" style="width:100%; border-collapse: collapse; font-size:10pt;">
                <thead>
                    <tr>
                        <th>Sr.no</th>
                        <th>Borrower Name</th>
                        <th>Payment Amount</th>
                        <th>Penalty</th>
                        <th>Referral Share</th>
                        <th>Payment Mode</th>
                        <th>Received Date</th>
                        <th>Due Date</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>';
    foreach ($data as $row) {
        $html .= '<tr>';
        foreach ($row as $cell) {
            $html .= "<td>$cell</td>";
        }
        $html .= '</tr>';
    }
    $html .= '</tbody>
            </table>';

    // Add HTML to PDF
    $pdf->writeHTML($html, true, false, true, false, '');
    $filename = "Loan_Report_" . date("Y-m-d_H-i-s") . ".pdf";

    // Output to browser
    $pdf->Output($filename, 'D');
    exit;
}
