<?php
require_once "../config.php";
require_once "../vendor/autoload.php";
include_once "../classes/class.Input.php";
include_once "../classes/LoanPaymentManager.php";

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use TCPDF;

$iTotalLoanAmount = 0;
$iTotalPenalty = 0;
$iTotalReferral = 0;

if (isset($_GET['export'])) {
    $exportType = $_GET['export'];
    $name = Input::request('name') ?? '';
    $dFromDate = Input::request('sFromDate') ?? '';
    $dToDate = Input::request('sToDateFilter') ?? '';
    $paymentMode = Input::request('paymentMode') ?? '';

    $oLoanPaymentManager = new LoanPaymentManager();
    $paymentData = $oLoanPaymentManager->getAllLoanPaymentsGlobal($name, $dFromDate, $dToDate, $paymentMode);

    foreach ($paymentData as $value) {
        $iTotalLoanAmount += $value['payment_amount'];
        $iTotalPenalty += $value['penalty_amount'];
        $iTotalReferral += $value['referral_share_amount'];
    }

    $filteredData = array_map(function ($loan, $index) {
        return [
            'Sr. No'            => $index + 1,
            'Borrower Name'     => $loan['name'] ?? '',
            'Payment Amount'    => number_format((float)($loan['payment_amount'] ?? 0), 2),
            'Penalty'           => number_format((float)($loan['penalty_amount'] ?? 0), 2),
            'Referral Share'    => number_format((float)($loan['referral_share_amount'] ?? 0), 2),
            'Payment Mode'      => $loan['mode_of_payment'] ?? '',
            'Comments'          => ucfirst($loan['comments']) ?? '',
            'Received Date'     => date('M d Y', strtotime($loan['received_date'] ?? '')),
            'Due Date'          => date('M d Y', strtotime($loan['interest_date'] ?? '')),
            'Status'            => ucfirst($loan['payment_status'] ?? 'Unknown'),
        ];
    }, $paymentData, array_keys($paymentData));

    $totals = [
        'Sr. No' => '',
        'Borrower Name' => 'Total',
        'Payment Amount' => number_format($iTotalLoanAmount, 2),
        'Penalty' => number_format($iTotalPenalty, 2),
        'Referral Share' => number_format($iTotalReferral, 2),
        'Payment Mode' => '',
        'Comments' => '',
        'Received Date' => '',
        'Due Date' => '',
        'Status' => '',
    ];

    $filteredData[] = $totals;

    if ($exportType === 'excel') {
        exportToExcel($filteredData);
    } elseif ($exportType === 'pdf') {
        exportToPDF($filteredData);
    }
}

function exportToExcel($data)
{
    $spreadsheet = new Spreadsheet();
    $sheet = $spreadsheet->getActiveSheet();

    $sheet->setCellValue('A1', 'Loan Payment Report');
    $sheet->mergeCells('A1:J1');
    $sheet->getStyle('A1')->getFont()->setBold(true)->setSize(14);
    $sheet->getRowDimension('1')->setRowHeight(30);

    $headers = array_keys($data[0]);
    $sheet->fromArray($headers, null, 'A2');

    $row = 3;
    foreach ($data as $record) {
        $sheet->fromArray(array_values($record), null, "A$row");
        $row++;
    }

    foreach (range('A', 'J') as $col) {
        $sheet->getColumnDimension($col)->setAutoSize(true);
    }

    $writer = new Xlsx($spreadsheet);
    $filename = "Loan_Report_" . date("Y-m-d_H-i-s") . ".xlsx";

    header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    header("Content-Disposition: attachment; filename=$filename");
    $writer->save("php://output");
    exit;
}

function exportToPDF($data)
{
    $pdf = new TCPDF();
    $pdf->SetCreator(PDF_CREATOR);
    $pdf->SetAuthor('SM Loan');
    $pdf->SetTitle('Loan Payment Report');
    $pdf->SetHeaderData('', 0, 'Loan Payment Report', 'Generated by SM Loan', [0, 64, 255], [0, 64, 128]);
    $pdf->setFooterData([0, 64, 0], [0, 64, 128]);
    $pdf->SetMargins(10, 20, 10);
    $pdf->SetHeaderMargin(5);
    $pdf->SetFooterMargin(10);
    $pdf->SetAutoPageBreak(true, 20);
    $pdf->AddPage();

    $html = '<h2 style="text-align:center;">Loan Payment Report</h2>';
    $html .= '<table border="1" cellpadding="5" cellspacing="0" style="width:100%; border-collapse: collapse; font-size:10pt;">
                <thead>
                    <tr>';

    foreach (array_keys($data[0]) as $header) {
        $html .= "<th>$header</th>";
    }

    $html .= '</tr></thead><tbody>';

    foreach ($data as $row) {
        $html .= '<tr>';
        foreach ($row as $cell) {
            $html .= "<td>$cell</td>";
        }
        $html .= '</tr>';
    }

    $html .= '</tbody></table>';

    $pdf->writeHTML($html, true, false, true, false, '');
    $filename = "Loan_Report_" . date("Y-m-d_H-i-s") . ".pdf";

    $pdf->Output($filename, 'D');
    exit;
}
