<?php
require_once '../config.php';
require_once '../vendor/autoload.php';
include_once '../classes/class.Input.php';
include_once '../classes/LoanPaymentManager.php';

use TCPDF;

$iPaymentId = Input::request("payment_id") ? Input::request("payment_id") : 0;
$oResult = (new LoanPaymentManager())->getLoanPaymentAndUserById($iPaymentId);

function generateLoanPaymentReceipt($oResult)
{
    // Initialize PDF object
    $pdf = new TCPDF();
    $pdf->SetCreator(PDF_CREATOR);
    $pdf->SetAuthor('SM Loan');
    $pdf->SetTitle('Loan Payment Receipt');
    $pdf->SetHeaderData('', 0, 'Loan Payment Receipt', 'Generated by SM Loan', [0, 64, 255], [0, 64, 128]);
    $pdf->setFooterData([0, 64, 0], [0, 64, 128]);
    $pdf->SetMargins(10, 20, 10);
    $pdf->SetHeaderMargin(5);
    $pdf->SetFooterMargin(10);
    $pdf->SetAutoPageBreak(true, 20);
    $pdf->AddPage();

    $cellHeight = 8; // standard cell height

    /* -------------------------
       Title Section
    ------------------------- */
    $pdf->SetFont('helvetica', 'B', 18);
    $pdf->SetTextColor(26, 115, 232);
    $pdf->Cell(0, 10, 'Loan Payment Receipt', 0, 1, 'C');
    $pdf->Ln(2);

    /* -------------------------
       Receipt Details Section
    ------------------------- */
    $pdf->SetFont('helvetica', 'B', 14);
    $pdf->SetTextColor(0, 0, 0);
    $pdf->Cell(0, $cellHeight, 'Receipt Details', 0, 1, 'L');
    $pdf->SetFont('helvetica', '', 12);
    // Set fill and border colors
    $pdf->SetFillColor(249, 249, 249);
    $pdf->SetDrawColor(221, 221, 221);

    // Row 1: Receipt No. & Receipt Date
    $cellWidth = 95;
    $pdf->Cell($cellWidth, $cellHeight, 'Receipt No.: ' . $oResult['payment_id'], 1, 0, 'L', 1);
    $pdf->Cell($cellWidth, $cellHeight, 'Receipt Date: ' . date("M d, Y", strtotime($oResult['received_date'])), 1, 1, 'R', 1);
    // Row 2: Payment Mode & Payment Status
    $pdf->Cell($cellWidth, $cellHeight, 'Payment Mode: ' . $oResult['mode_of_payment'], 1, 0, 'L', 1);
    $pdf->Cell($cellWidth, $cellHeight, 'Payment Status: ' . $oResult['payment_status'], 1, 1, 'R', 1);

    $pdf->Ln(5);

    /* -------------------------
       Borrower Details Section
    ------------------------- */
    $pdf->SetFont('helvetica', 'B', 14);
    $pdf->Cell(0, $cellHeight, 'Borrower Details', 0, 1, 'L');
    $pdf->SetFont('helvetica', '', 12);
    // Row 1: Borrower ID & Name
    $pdf->Cell($cellWidth, $cellHeight, 'Borrower ID: ' . $oResult['unique_borrower_id'], 1, 0, 'L', 1);
    $pdf->Cell($cellWidth, $cellHeight, 'Name: ' . $oResult['name'], 1, 1, 'R', 1);
    // Row 2: Phone & Email
    $pdf->Cell($cellWidth, $cellHeight, 'Phone: ' . $oResult['phone_no'], 1, 0, 'L', 1);
    $pdf->Cell($cellWidth, $cellHeight, 'Email: ' . $oResult['email'], 1, 1, 'R', 1);
    // Row 3: Address (full width)
    $pdf->Cell(0, $cellHeight, 'Address: ' . $oResult['address'], 1, 1, 'L', 1);

    $pdf->Ln(5);

    /* -------------------------
       Loan Overview Section
    ------------------------- */
    $pdf->SetFont('helvetica', 'B', 14);
    $pdf->Cell(0, $cellHeight, 'Loan Details', 0, 1, 'L');
    $pdf->SetFont('helvetica', '', 12);
    // Row 1: Loan Amount & Interest Rate
    $pdf->Cell($cellWidth, $cellHeight, 'Loan Amount: Rs. ' . number_format($oResult['principal_amount'], 2), 1, 0, 'L', 1);
    $pdf->Cell($cellWidth, $cellHeight, 'Interest Rate: ' . number_format($oResult['interest_rate'], 2) . '%', 1, 1, 'R', 1);
    // Row 2: Loan Period & Disbursed Date
    $pdf->Cell($cellWidth, $cellHeight, 'Loan Period: ' . $oResult['loan_period'] . ' Month', 1, 0, 'L', 1);
    $pdf->Cell($cellWidth, $cellHeight, 'Disbursed: ' . date("M d, Y", strtotime($oResult['disbursed_date'])), 1, 1, 'R', 1);
    // Row 3: EMI Amount & Closure Date
    // $pdf->Cell($cellWidth, $cellHeight, 'EMI Amount: Rs. ' . number_format($oResult['EMI_amount'], 2), 1, 0, 'L', 1);
    $pdf->Cell($cellWidth, $cellHeight, 'Closure Date: ' . date("M d, Y", strtotime($oResult['closure_date'])), 1, 0, 'L', 1);
    // Optionally, show Closure Amount if needed
    // $pdf->Cell(0, $cellHeight, 'Closure Amount: Rs. ' . number_format($oResult['closure_amount'], 2), 1, 1, 'L', 1);

    $pdf->Ln(10);

    /* -------------------------
       Payment Summary Section
    ------------------------- */
    $pdf->SetFont('helvetica', 'B', 14);
    $pdf->Cell(0, $cellHeight, 'Payment Summary', 0, 1, 'L');
    $pdf->SetFont('helvetica', 'B', 12);
    // Table Header
    $pdf->SetFillColor(242, 242, 242);
    $pdf->Cell(20, $cellHeight, 'Sr. No', 1, 0, 'C', 1);
    $pdf->Cell(80, $cellHeight, 'Loan Head', 1, 0, 'C', 1);
    $pdf->Cell(90, $cellHeight, 'Amount (Rs)', 1, 1, 'C', 1);
    
    // Table Body - using white background for rows
    $pdf->SetFillColor(255, 255, 255);
    $pdf->SetFont('helvetica', '', 12);
    // Row 1: Principal Paid
    $pdf->Cell(20, $cellHeight, '1', 1, 0, 'C', 1);
    $pdf->Cell(80, $cellHeight, 'Principal Paid', 1, 0, 'L', 1);
    $pdf->Cell(90, $cellHeight, number_format($oResult['principal_paid'], 2), 1, 1, 'R', 1);
    // Row 2: Interest Paid
    $pdf->Cell(20, $cellHeight, '2', 1, 0, 'C', 1);
    $pdf->Cell(80, $cellHeight, 'Interest Paid', 1, 0, 'L', 1);
    $pdf->Cell(90, $cellHeight, number_format($oResult['interest_paid'], 2), 1, 1, 'R', 1);
    // Row 3: Penalty Amount
    $pdf->Cell(20, $cellHeight, '3', 1, 0, 'C', 1);
    $pdf->Cell(80, $cellHeight, 'Penalty Amount', 1, 0, 'L', 1);
    $pdf->Cell(90, $cellHeight, number_format($oResult['penalty_amount'], 2), 1, 1, 'R', 1);
    // Row 4: Referral Share
    $pdf->Cell(20, $cellHeight, '4', 1, 0, 'C', 1);
    $pdf->Cell(80, $cellHeight, 'Referral Share', 1, 0, 'L', 1);
    $pdf->Cell(90, $cellHeight, number_format($oResult['referral_share_amount'], 2), 1, 1, 'R', 1);
    
    // Final Amount row
    $pdf->SetFont('helvetica', 'B', 12);
    $pdf->SetFillColor(242, 242, 242);
    $pdf->Cell(100, $cellHeight, 'Final Amount (Rs.)', 1, 0, 'L', 1);
    $pdf->Cell(90, $cellHeight, number_format($oResult['final_amount'], 2), 1, 1, 'R', 1);

    $pdf->Ln(10);
    
    /* -------------------------
       Footer Message
    ------------------------- */
    $pdf->SetFont('helvetica', 'I', 10);
    $pdf->SetTextColor(119, 119, 119);
    $pdf->Cell(0, $cellHeight, 'This is a computerized receipt, so signature is not required.', 0, 1, 'C');

    // Generate and output the PDF
    $filename = "Loan_Payment_Receipt_" . date("Y-m-d_H-i-s") . ".pdf";
    $pdf->Output($filename, 'D');
    exit;
}

generateLoanPaymentReceipt($oResult);
