<?php
require_once "../config.php";
require_once "../vendor/autoload.php";
include "../classes/ReferralUserManager.php";

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use TCPDF;

if (isset($_GET['export'])) {
    $exportType = $_GET['export'];
    $aData['sName'] = $_REQUEST['name'] ? $_REQUEST['name'] :'';

    // Fetch referral details
    $referrals = (new ReferralUserManager())->getAllReferralUsers($aData);

    // Map and filter required columns
    $filteredReferrals = array_map(function ($referral, $index) {
        return [
            'Sr. No'          => $index + 1,
            'Referral Name'   => $referral['ref_name'] ?? '',
            'Phone Number'    => $referral['ref_phone_number'] ?? '',
            'Percentage (%)'  => $referral['ref_percentage'] ?? '',
            'Added On'        => date($referral['added_on']) ?? '',
        ];
    }, $referrals, array_keys($referrals));

    if ($exportType === 'excel') {
        exportToExcel($filteredReferrals);
    } elseif ($exportType === 'pdf') {
        exportToPDF($filteredReferrals);
    }
}

function exportToExcel($data) {
    $spreadsheet = new Spreadsheet();
    $sheet = $spreadsheet->getActiveSheet();

    // Set title and headings
    $sheet->setCellValue('A1', 'Referral Details Report');
    $sheet->mergeCells('A1:E1');
    $sheet->getStyle('A1')->getFont()->setBold(true)->setSize(14);
    $sheet->getRowDimension('1')->setRowHeight(30);

    // Add header row
    $headers = array_keys($data[0]);
    $sheet->fromArray($headers, null, 'A2');

    // Add data rows
    $row = 3;
    foreach ($data as $referral) {
        $sheet->fromArray(array_values($referral), null, "A$row");
        $row++;
    }

    // Auto-size columns and wrap text
    foreach (range('A', 'E') as $col) {
        $sheet->getColumnDimension($col)->setAutoSize(true);
        $sheet->getStyle($col . '2:' . $col . $row)->getAlignment()->setWrapText(true);
    }

    // Write file
    $writer = new Xlsx($spreadsheet);
    $filename = "Referral_Report_" . date("Y-m-d_H-i-s") . ".xlsx";

    // Output to browser
    header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    header("Content-Disposition: attachment; filename=$filename");
    $writer->save("php://output");
    exit;
}

function exportToPDF($data) {
    $pdf = new TCPDF();
    $pdf->SetCreator(PDF_CREATOR);
    $pdf->SetAuthor('Referral Management System');
    $pdf->SetTitle('Referral Report');
    $pdf->SetHeaderData('', 0, 'Referral Report', 'Generated by Referral Management System', [0, 64, 255], [0, 64, 128]);
    $pdf->setFooterData([0, 64, 0], [0, 64, 128]);
    $pdf->SetMargins(10, 20, 10);
    $pdf->SetHeaderMargin(5);
    $pdf->SetFooterMargin(10);
    $pdf->SetAutoPageBreak(true, 20);
    $pdf->AddPage();

    // Generate table HTML
    $html = '<h2 style="text-align:center;">Referral Report</h2>';
    $html .= '<table border="1" cellpadding="5" cellspacing="0" style="width:100%; border-collapse: collapse; font-size:10pt;">
                <thead>
                    <tr>
                        <th scope="col">Sr. No</th>
                        <th scope="col">Referral Name</th>
                        <th scope="col">Phone Number</th>
                        <th scope="col">Percentage (%)</th>
                        <th scope="col">Added On</th>
                    </tr>
                </thead>
                <tbody>';
    foreach ($data as $row) {
        $html .= '<tr>';
        foreach ($row as $cell) {
            $html .= "<td>$cell</td>";
        }
        $html .= '</tr>';
    }
    $html .= '</tbody>
            </table>';

    // Add HTML to PDF
    $pdf->writeHTML($html, true, false, true, false, '');
    $filename = "Referral_Report_" . date("Y-m-d_H-i-s") . ".pdf";

    // Output to browser
    $pdf->Output($filename, 'D');
    exit;
}
?>
